GET http://localhost:5075/orders
//ctrl alt R to send request

###
GET http://localhost:5075/orders/2

###
POST http://localhost:5075/orders
Content-Type: application/json

//payload
{
    "CustomerId": "Jotaro",
    "DateOrder": "2011-11-18",
    "TotalPrice": 600.99,
    "OrderInfoId": 2
}

###
PUT http://localhost:5075/orders/2
Content-Type: application/json

//payload to update
//becareful sa Names ng variables kasi d mababasa ng controllers
{
    "CustomerId": "Jana",
    "OrderDate": "2001-10-1",
    "TotalPrice": 800,
    "OrderInfo": ["Kikiam"]
}

###
DELETE http://localhost:5075/orders/8