GET http://localhost:5075/orders
//ctrl alt R to send request

###
GET http://localhost:5075/orders/2

###
POST http://localhost:5075/orders
Content-Type: application/json

//payload
{
    "CustomerId": "Jotaro",
    "DateOrder": "2011-11-18",
    "TotalPrice": 69.99,
    "OrderInfoId": 3
}

###
PUT http://localhost:5075/orders/3
Content-Type: application/json

//payload to update
//becareful sa Names ng variables kasi d mababasa ng controllers
{
    "CustomerId": "Junjun",
    "DateOrder": "2001-10-01",
    "TotalPrice": 800.91,
    "OrderInfoId": 2
}

###
DELETE http://localhost:5075/orders/3